spring.application.name=uniride-routes-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/uniride_routes
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clave secreta compartida con uniride-iam-service (¡Debe ser la misma!)
jwt.secret=ThisIsASecretKeyForCampusDriveAppThatMustBeVeryLongAndSecure

# API Key de OpenRouteService (Reemplaza con la tuya)
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjY2OGJjMzg5NWIxMjQ4ZGU5ZTg4ZjAxNDI5NjgxNjU1IiwiaCI6Im11cm11cjY0In0=

springdoc.swagger-ui.path=/swagger-ui.html